
import os
import subprocess

scripts = [
    "generate_actions_sheet.py",
    "generate_action_patterns_sheet.py",
    "generate_behavior_sheet.py",
    "generate_calc_sheet.py",
    "generate_cases_sheet.py",
    "generate_connections_sheet.py",
    "generate_constraints_sheet.py",
    "generate_graphical_sheet.py",
    "generate_index_sheet.py",
    "generate_patterns_sheet.py",
    "generate_reference_sheet.py",
    "generate_requirements_sheet.py",
    "generate_shorthand_sheet.py",
    "generate_states_sheet.py",
    "generate_state_patterns_sheet.py",
    "generate_metadata_sheet.py",
    "generate_use_case_tutorial.py",
    "generate_naming_tutorial.py",
    "generate_core_types_tutorial.py",
    "generate_semantic_metadata_tutorial.py",
    "generate_features_tutorial.py",
    "generate_parts_attributes_tutorial.py"
]

# --- Cleanup ---
output_dir = os.path.join("output", "pastableExamples")
if os.path.exists(output_dir):
    print(f"Cleaning {output_dir}...")
    for f in os.listdir(output_dir):
        if f.endswith(".sysml"):
            os.remove(os.path.join(output_dir, f))
else:
    os.makedirs(output_dir, exist_ok=True)

for script in scripts:
    print(f"Running {script}...")
    try:
        subprocess.run(["py", script], check=True, cwd="src")
    except Exception as e:
        print(f"Error running {script}: {e}")

# --- Merge Logic ---
print("Merging examples...")
output_dir = os.path.join("output", "pastableExamples")
merged_file_path = os.path.join(output_dir, "MergedExamples.sysml")

if os.path.exists(output_dir):
    try:
        with open(merged_file_path, "w", encoding="utf-8") as outfile:
            # Add file header
            outfile.write("// Merged SysML v2 Examples\n")
            outfile.write("// Generated by SysMLv2CheatSheet Generator\n\n")
            
            # Iterate over files
            files = sorted([f for f in os.listdir(output_dir) if f.endswith(".sysml") and f != "MergedExamples.sysml"])
            for filename in files:
                file_path = os.path.join(output_dir, filename)
                with open(file_path, "r", encoding="utf-8") as infile:
                    outfile.write(f"// --- Source: {filename} ---\n")
                    outfile.write(infile.read())
                    outfile.write("\n\n")
        print(f"Successfully created {merged_file_path}")
    except Exception as e:
        print(f"Error merging files: {e}")
else:
    print(f"Warning: Directory not found for merging: {output_dir}")
