import os
import glob
import datetime

def combine_markdown_files(source_dir, output_file, title):
    """
    Combines all .md files in the source_dir into a single output_file.
    """
    # Find all .md files
    md_files = glob.glob(os.path.join(source_dir, "*.md"))
    
    # Sort files to ensure deterministic order. 
    # Logic: Try to sort by leading number if possible, else alphabetical.
    def sort_key(f):
        basename = os.path.basename(f)
        # Check for tutorial prefixes like "01_Foundations.md" (if they existed)
        # But currently tutorials like "use_case_tutorial.md" don't have numbers.
        # We might want a custom order list, or just alphabetical.
        # For now, alphabetical is safer than random.
        return basename

    md_files.sort(key=sort_key)
    
    with open(output_file, 'w', encoding='utf-8') as outfile:
        # Title Page
        outfile.write(f"# {title}\n\n")
        outfile.write(f"**Generated on:** {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n\n")
        outfile.write("---\n\n")
        
        # Table of Contents (Auto-generated by many readers, but we can list files)
        outfile.write("## Table of Contents\n\n")
        for f in md_files:
            basename = os.path.basename(f).replace(".md", "").replace("_", " ").title()
            outfile.write(f"- {basename}\n")
        outfile.write("\n---\n\n")
        
        for f in md_files:
            # Add a separator
            basename = os.path.basename(f).replace(".md", "").replace("_", " ").title()
            outfile.write(f"<div style='page-break-before: always;'></div>\n\n") # Force page break for PDF
            outfile.write(f"# {basename}\n\n")
            
            try:
                with open(f, 'r', encoding='utf-8') as infile:
                    content = infile.read()
                    # Optional: Demote headers if needed? 
                    # If individual files start with # Header, they become top level.
                    # That is fine if we want them to be top level chapters.
                    outfile.write(content)
                    outfile.write("\n\n")
            except Exception as e:
                print(f"Error reading {f}: {e}")
                
    print(f"Successfully created {output_file} from {len(md_files)} files.")

def main():
    base_dir = os.path.dirname(os.path.abspath(__file__))
    output_base = os.path.join(base_dir, "..", "output")
    
    # 1. Combine Tutorials
    tutorials_dir = os.path.join(output_base, "tutorials")
    tutorials_out = os.path.join(output_base, "SysMLv2_All_Tutorials.md")
    
    if os.path.exists(tutorials_dir):
        print(f"Combining tutorials from {tutorials_dir}...")
        combine_markdown_files(tutorials_dir, tutorials_out, "SysML v2 Tutorials: Complete Collection")
    else:
        print(f"Warning: Tutorials directory not found: {tutorials_dir}")

    # 2. Combine Cheat Sheets
    cheatsheets_dir = os.path.join(output_base, "cheatsheets")
    cheatsheets_out = os.path.join(output_base, "SysMLv2_All_CheatSheets.md")
    
    if os.path.exists(cheatsheets_dir):
        print(f"Combining cheat sheets from {cheatsheets_dir}...")
        combine_markdown_files(cheatsheets_dir, cheatsheets_out, "SysML v2 Cheat Sheets: Complete Collection")
    else:
        print(f"Warning: Cheat sheets directory not found: {cheatsheets_dir}")

    # 3. Combine into a single skill.md
    llm_skills_dir = os.path.join(base_dir, "..", "LLM_skills")
    os.makedirs(llm_skills_dir, exist_ok=True)
    skill_out = os.path.join(llm_skills_dir, "skill.md")
    reference_file = os.path.join(base_dir, "..", "SysMLv2_Language_Reference.md")
    print(f"Combining everything into {skill_out}...")
    try:
        with open(skill_out, 'w', encoding='utf-8') as outfile:
            outfile.write("# SysML v2 AI Agent Skill / Comprehensive Reference\n\n")
            outfile.write(f"**Generated on:** {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n\n")
            outfile.write("---\n\n")
            
            # Add Language Reference
            if os.path.exists(reference_file):
                with open(reference_file, 'r', encoding='utf-8') as ref_in:
                    outfile.write(ref_in.read())
                    outfile.write("\n\n---\n\n")
            
            # Add Cheat Sheets
            if os.path.exists(cheatsheets_out):
                with open(cheatsheets_out, 'r', encoding='utf-8') as cs_in:
                    outfile.write(cs_in.read())
                    outfile.write("\n\n---\n\n")
            
            # Add Tutorials
            if os.path.exists(tutorials_out):
                with open(tutorials_out, 'r', encoding='utf-8') as tut_in:
                    outfile.write(tut_in.read())
                    outfile.write("\n\n")
        print(f"Successfully created {skill_out}")
    except Exception as e:
        print(f"Error creating skill.md: {e}")

if __name__ == "__main__":
    main()
